### ISSUE TITLE
structs implementing `ValueDecoder` force reflect lookup on every Decode

### ISSUE THREAD

**Issue by tsholmes** [segmentio/objconv#24]
![screen shot 2018-04-13 at 5 24 47 pm](https://user-images.githubusercontent.com/2865426/38762338-ae45d744-3f3f-11e8-821e-4b31157380f2.png)

**Comment by achille-roussel** [comment]
Do you have a code example to reproduce the issue?

**Comment by tsholmes** [comment]
This turned out to be a really poor sample size. It has to make a reflection call because its taking in an `interface{}`. On a higher throughput process this turned out to be a really small amount of time.
