### ISSUE TITLE
Doesn't Follow Tags

### ISSUE THREAD

**Issue by thehydroimpulse** [segmentio/objconv#9]
cc @achille-roussel 

Just spotted this issue and just swapped back to the stdlib version (don't have time to look into it right now).

```golang
stdlib: {"event":{},"settings":{}}
objconv: {"Event":{},"Settings":{}}
```

**Comment by achille-roussel** [comment]
You gotta use the objconv tag instead of json.

**Comment by thehydroimpulse** [comment]
🔥
